version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-rs
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: |
        mongosh --eval '
          try {
            rs.status().ok
          } catch (e) {
            rs.initiate({
              _id: "rs0",
              members: [{ _id: 0, host: "mongo-rs:27017" }]
            }).ok
          }
        ' --quiet
      interval: 5s
      timeout: 30s
      start_period: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
