name: MERN Sandbox CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Run setup via make
      run: make setup

    - name: Run linting via make
      run: make lint

    - name: Run tests via make
      run: make test

    - name: Build production image
      run: make build

    - name: Stop services
      if: always() # Always run this step to clean up, even if previous steps fail
      run: make stop
